# Site settings
title: chemiczka.pl | Korepetycje z chemii
description: "Korepetycje z chemii, eksperymenty chemiczne"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chemiczka.pl" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: chemiczka.pl
    hero_description: Cześć, mam na imię Karolina. Jestem chemiczką. Chętnie pomogę Ci zrozumieć chemię.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency:
    email: contact@yoursite.com
    address: ul. Geodetów, <br> Warszawa, Ochota

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Geodetów 6, Warszawa, Polska
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2016 chemiczka.pl - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-43040992-3
google_verification:
